
name = "nexus-crm"
compatibility_date = "2024-12-01"

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "nexus-db"
database_id = "5d087172-7960-4d47-9606-16c395e21923"

[observability]
enabled = true
